### ISSUE TITLE
NameError: name 'obj' is not defined

### ISSUE THREAD

**Issue by mazin-hnewa** [stevewongv/SPANet#9]
When I want to test your model with your test data set (Real_Internet, real_test_1000), I get this error:
2019-08-11 21:25:44,906 - INFO - set log dir as ./logdir
2019-08-11 21:25:44,906 - INFO - set model dir as ./model
Traceback (most recent call last):
  File "main.py", line 297, in <module>
    run_test(args.model)
  File "main.py", line 251, in run_test
    sess.load_checkpoints(ckp_name,'test')
  File "main.py", line 121, in load_checkpoints
    self.step = obj['clock']
**NameError: name 'obj' is not defined**

Could you please tell me how can I solve this problem

**Comment by stevewongv** [comment]
I have fixed this, please re-download the code. Thank you!
